export const ERROR_CODE = {
	BAD_REQUEST: 'BAD_REQUEST',
	NOT_FOUND: 'NOT_FOUND',
	UNIQUE_CONSTAINT: 'UNIQUE_CONSTAINT',
    DUPLICATE: 'DUPLICATE',
    TOKEN_INVALID: 'TOKEN_INVALID',
    FORBIDDEN: 'FORBIDDEN',
    INTERNAL: 'INTERNAL',
    UNPROCESSABLE_ENTITY: 'UNPROCESSABLE_ENTITY'
}